In [1]:
import pandas as pd
import numpy as np

# Definir o número de linhas
n_rows = 500

# Gerar dados fictícios
data = {
    'temperatura_interna_celsius': np.random.uniform(20.0, 25.0, n_rows),
    'temperatura_externa_celsius': np.random.uniform(-150.0, 120.0, n_rows),
    'integridade_estrutural': np.random.choice([0, 1], n_rows, p=[0.3, 0.7]),
    'niveis_energia_percentual': np.random.uniform(0.0, 100.0, n_rows),
    'pressao_tanques_psi': np.random.uniform(50.0, 185.0, n_rows),
    'status_modulos_criticos': np.random.choice(['Normal', 'Atenção', 'Crítico'], n_rows, p=[0.7, 0.25, 0.05])

}


# Criar o DataFrame
df_ficticio = pd.DataFrame(data)

df_ficticio.to_csv('dados_ficticios.csv', index=False)

In [2]:
import pandas as pd
import numpy as np

n_rows = 500


data_energia = {
    'Capacidade total (kwh)': np.random.uniform(2000, 10000, n_rows),
    'Carga atual (%)': np.random.uniform(60.0, 100.0, n_rows),
    'Consumo estimado na decolagem (kwh)': np.random.uniform(500, 2000, n_rows),
    'Perdas energéticas (kwh)': np.random.uniform(50, 300, n_rows)
}

df_analise_energia = pd.DataFrame(data_energia)

df_analise_energia.to_csv('analise_energia.csv', index=False)

In [3]:
from os import abort
dados=pd.read_csv('dados_ficticios.csv')

def decisão(row):
  cond_integridade = (row["integridade_estrutural"] == 1)
  cond_energia = (row["niveis_energia_percentual"] >= 70.0)
  cond_pressao = (row["pressao_tanques_psi"] >= 50.0) and (row["pressao_tanques_psi"] <= 180.0)
  cond_modulo_status = (row["status_modulos_criticos"] == str("Normal"))
  cond_temperatura_interna = (row["temperatura_interna_celsius"] >= 20.0) and (row["temperatura_interna_celsius"] <= 25.0)
  cond_temperatura_externa = (row["temperatura_externa_celsius"] >= -152.0) and (row["temperatura_externa_celsius"] <= 125.0)

  failed_conditions = []
  if not cond_integridade:
    failed_conditions.append('Integridade Estrutural')
  if not cond_energia:
    failed_conditions.append('Níveis de Energia')
  if not cond_pressao:
    failed_conditions.append('Pressão dos Tanques')
  if not cond_modulo_status:
    failed_conditions.append('Status dos Módulos Críticos')
  if not cond_temperatura_interna:
    failed_conditions.append('Temperatura Interna')
  if not cond_temperatura_externa:
    failed_conditions.append('Temperatura Externa')

  if not failed_conditions:
    return 'PRONTO PARA DECOLAR', ''
  else:
    return 'DECOLAGEM ABORTADA', ', '.join(failed_conditions)

dados[['decisao', 'condicao_falha']] = dados.apply(lambda row: pd.Series(decisão(row)), axis=1)

ready = dados[dados['decisao'] == 'PRONTO PARA DECOLAR'].shape[0]

abort = dados[dados['decisao'] == 'DECOLAGEM ABORTADA'].shape[0]

print(f"Quantidade de decisões 'PRONTO PARA DECOLAR': {ready}")
print(f"Quantidade de decisões 'DECOLAGEM ABORTADA': {abort}")

print(f"Porcentagem de decisões 'PRONTO PARA DECOLAR': {ready / dados.shape[0] * 100:.2f}%")
print(f"Porcentagem de decisões 'DECOLAGEM ABORTADA': {abort / dados.shape[0] * 100:.2f}%")

print(f"pProporção (1 para x) 'PRONTO PARA DECOLAR': {dados.shape[0] / ready:.2f}")
print(f"Proporção (1 para x) 'DECOLAGEM ABORTADA': {dados.shape[0] / abort:.2f}")

display(dados.head(16))

Quantidade de decisões 'PRONTO PARA DECOLAR': 73
Quantidade de decisões 'DECOLAGEM ABORTADA': 427
Porcentagem de decisões 'PRONTO PARA DECOLAR': 14.60%
Porcentagem de decisões 'DECOLAGEM ABORTADA': 85.40%
pProporção (1 para x) 'PRONTO PARA DECOLAR': 6.85
Proporção (1 para x) 'DECOLAGEM ABORTADA': 1.17

,temperatura_interna_celsius,temperatura_externa_celsius,integridade_estrutural,niveis_energia_percentual,pressao_tanques_psi,status_modulos_criticos,decisao,condicao_falha
0,20.763633,7.984980,1,54.862106,158.181313,Normal,DECOLAGEM ABORTADA,Níveis de Energia
1,24.252524,-10.000237,0,17.196461,102.055010,Normal,DECOLAGEM ABORTADA,"Integridade Estrutural, Níveis de Energia"
2,23.496355,-124.507890,1,50.906128,70.613462,Crítico,DECOLAGEM ABORTADA,"Níveis de Energia, Status dos Módulos Críticos"
3,20.185793,-74.501496,1,98.743591,58.455258,Normal,PRONTO PARA DECOLAR,
4,21.980742,-65.392230,0,77.368710,103.360492,Normal,DECOLAGEM ABORTADA,Integridade Estrutural
5,23.042971,-22.879292,1,9.117168,68.969908,Normal,DECOLAGEM ABORTADA,Níveis de Energia
6,22.566838,-88.508552,1,25.290754,175.231197,Atenção,DECOLAGEM ABORTADA,"Níveis de Energia, Status dos Módulos Críticos"
7,20.891059,-64.124406,1,60.668812,183.441781,Normal,DECOLAGEM ABORTADA,"Níveis de Energia, Pressão dos Tanques"
8,23.022941,69.586598,0,11.692412,135.365421,Normal,DECOLAGEM ABORTADA,"Integridade Estrutural, Níveis de Energia"
9,24.432498,-35.856696,1,44.883325,97.999128,Normal,DECOLAGEM ABORTADA,Níveis de Energia
10,22.887934,23.993385,1,36.160713,93.488169,Normal,DECOLAGEM ABORTADA,Níveis de Energia
11,24.613894,-57.715665,1,89.719966,83.333213,Normal,PRONTO PARA DECOLAR,
12,22.187813,16.199828,1,79.634763,52.000121,Normal,PRONTO PARA DECOLAR,
13,23.508030,-90.547894,1,8.719369,61.401953,Normal,DECOLAGEM ABORTADA,Níveis de Energia
14,22.856073,40.132159,0,15.151642,51.329893,Normal,DECOLAGEM ABORTADA,"Integridade Estrutural, Níveis de Energia"
15,24.786807,61.628614,1,88.158059,122.646017,Normal,PRONTO PARA DECOLAR,

In [4]:
import pandas as pd

autonomiaI = pd.read_csv('analise_energia.csv')

autonomiaI['Carga atual (kwh)'] = autonomiaI['Capacidade total (kwh)'] *  (autonomiaI['Carga atual (%)'] / 100)

autonomiaI['Autonomia inicial (kwh)'] = autonomiaI['Carga atual (kwh)'] - autonomiaI['Consumo estimado na decolagem (kwh)'] - autonomiaI['Perdas energéticas (kwh)']

display(autonomiaI.head(16))

,Capacidade total (kwh),Carga atual (%),Consumo estimado na decolagem (kwh),Perdas energéticas (kwh),Carga atual (kwh),Autonomia inicial (kwh)
0,3958.003943,64.931537,1478.232160,279.755235,2569.992793,812.005398
1,8566.253955,81.516339,946.342890,212.997953,6982.896572,5823.555728
2,8592.060075,64.290726,703.100462,71.648622,5523.897786,4749.148702
3,8925.252373,75.051885,623.385003,135.978643,6698.570172,5939.206525
4,8761.490205,90.639059,1714.554665,280.900321,7941.332315,5945.877328
5,3534.596935,82.409919,1089.087448,111.188093,2912.858456,1712.582915
6,7691.910821,66.456919,1095.836665,199.578072,5111.806940,3816.392203
7,2018.011479,81.419202,627.948461,239.191959,1643.048841,775.908421
8,4404.022406,81.316734,758.301649,294.781888,3581.207186,2528.123649
9,6419.908528,62.666285,1664.034788,258.250524,4023.118170,2100.832858
10,6851.748953,70.947021,1302.920382,256.645915,4861.111791,3301.545494
11,4019.192982,85.160205,1646.791449,210.733727,3422.752986,1565.227810
12,6725.151704,77.163646,600.261899,282.153588,5189.372250,4306.956762
13,6253.727864,79.157528,601.885901,91.767106,4950.296409,4256.643402
14,4075.423834,76.849467,879.115961,220.866190,3131.941480,2031.959330
15,7715.008636,98.540972,1338.547844,187.399181,7602.444496,6076.497471

In [5]:
print('--- Visão Geral do Dataset (df.info()) ---')
df_ficticio.info()

print('\n--- Descrição Estatística do Dataset (df.describe()) ---\n')
df_ficticio.describe()

--- Visão Geral do Dataset (df.info()) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   temperatura_interna_celsius  500 non-null    float64
 1   temperatura_externa_celsius  500 non-null    float64
 2   integridade_estrutural       500 non-null    int64
 3   niveis_energia_percentual    500 non-null    float64
 4   pressao_tanques_psi          500 non-null    float64
 5   status_modulos_criticos      500 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 23.6+ KB

--- Descrição Estatística do Dataset (df.describe()) ---

,temperatura_interna_celsius,temperatura_externa_celsius,integridade_estrutural,niveis_energia_percentual,pressao_tanques_psi
count,500.000000,500.000000,500.000000,500.000000,500.000000
mean,22.605191,-14.324874,0.714000,50.108528,118.254525
std,1.470973,78.181140,0.452342,28.578871,39.249805
min,20.026538,-149.419732,0.000000,0.075293,50.115331
25%,21.350001,-84.010812,0.000000,25.826895,85.242761
50%,22.684174,-16.917067,1.000000,51.911509,119.075209
75%,23.914291,54.578072,1.000000,72.670229,151.932778
max,24.997781,119.778310,1.000000,99.931440,184.879306

In [6]:
print('--- Visão Geral do Dataset de Análise Energética (autonomiaI.info()) ---')
autonomiaI.info()

print('\n--- Descrição Estatística do Dataset de Análise Energética (autonomiaI.describe()) ---\n')
autonomiaI.describe()

--- Visão Geral do Dataset de Análise Energética (autonomiaI.info()) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Capacidade total (kwh)               500 non-null    float64
 1   Carga atual (%)                      500 non-null    float64
 2   Consumo estimado na decolagem (kwh)  500 non-null    float64
 3   Perdas energéticas (kwh)             500 non-null    float64
 4   Carga atual (kwh)                    500 non-null    float64
 5   Autonomia inicial (kwh)              500 non-null    float64
dtypes: float64(6)
memory usage: 23.6 KB

--- Descrição Estatística do Dataset de Análise Energética (autonomiaI.describe()) ---

,Capacidade total (kwh),Carga atual (%),Consumo estimado na decolagem (kwh),Perdas energéticas (kwh),Carga atual (kwh),Autonomia inicial (kwh)
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,6060.036091,79.675784,1235.775071,178.964923,4819.496738,3404.756743
std,2307.741204,11.570967,427.033247,71.050220,1961.022102,2004.096670
min,2000.702582,60.135909,505.194390,51.427180,1347.131125,-737.901295
25%,4073.113388,69.530418,885.621724,119.493783,3116.801906,1755.506288
50%,6123.687662,80.270543,1229.478116,183.002000,4820.140908,3335.797471
75%,8170.833436,89.477068,1602.936049,239.308233,6243.132058,4821.684209
max,9997.814795,99.906288,1995.157822,299.772184,9774.331216,8987.101710